### ISSUE TITLE
连接失败，并没有弹出adb授权弹框

### ISSUE THREAD

**Issue by Layne2016** [mingzhixian/Easycontrol#20]
连接时连接失败，被控端也没有弹出授权adb的弹框
```
2023-11-01 11:12:51.488  7314-9093  System.err              top.saymzx.easycontrol.app           W  java.net.ConnectException: failed to connect to /192.168.0.209 (port 5555) from /:: (port 40156): connect failed: ECONNREFUSED (Connection refused)
2023-11-01 11:12:51.488  7314-9093  System.err              top.saymzx.easycontrol.app           W  	at libcore.io.IoBridge.connect(IoBridge.java:188)
2023-11-01 11:12:51.488  7314-9093  System.err              top.saymzx.easycontrol.app           W  	at java.net.PlainSocketImpl.socketConnect(PlainSocketImpl.java:142)
2023-11-01 11:12:51.488  7314-9093  System.err              top.saymzx.easycontrol.app           W  	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:390)
2023-11-01 11:12:51.488  7314-9093  System.err              top.saymzx.easycontrol.app           W  	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:230)
2023-11-01 11:12:51.488  7314-9093  System.err              top.saymzx.easycontrol.app           W  	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:212)
2023-11-01 11:12:51.488  7314-9093  System.err              top.saymzx.easycontrol.app           W  	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:436)
2023-11-01 11:12:51.489  7314-9093  System.err              top.saymzx.easycontrol.app           W  	at java.net.Socket.connect(Socket.java:621)
2023-11-01 11:12:51.489  7314-9093  System.err              top.saymzx.easycontrol.app           W  	at java.net.Socket.connect(Socket.java:570)
2023-11-01 11:12:51.489  7314-9093  System.err              top.saymzx.easycontrol.app           W  	at top.saymzx.easycontrol.adb.TcpChannel.<init>(TcpChannel.java:16)
2023-11-01 11:12:51.489  7314-9093  System.err              top.saymzx.easycontrol.app           W  	at top.saymzx.easycontrol.adb.Adb.<init>(Adb.java:24)
2023-11-01 11:12:51.489  7314-9093  System.err              top.saymzx.easycontrol.app           W  	at top.saymzx.easycontrol.app.client.Client.connectADB(Client.java:112)
2023-11-01 11:12:51.489  7314-9093  System.err              top.saymzx.easycontrol.app           W  	at top.saymzx.easycontrol.app.client.Client.lambda$new$2$top-saymzx-easycontrol-app-client-Client(Client.java:60)
2023-11-01 11:12:51.489  7314-9093  System.err              top.saymzx.easycontrol.app           W  	at top.saymzx.easycontrol.app.client.Client$$ExternalSyntheticLambda4.run(Unknown Source:6)
2023-11-01 11:12:51.489  7314-9093  System.err              top.saymzx.easycontrol.app           W  	at java.lang.Thread.run(Thread.java:920)
2023-11-01 11:12:51.490  7314-9093  System.err              top.saymzx.easycontrol.app           W  Caused by: android.system.ErrnoException: connect failed: ECONNREFUSED (Connection refused)
2023-11-01 11:12:51.490  7314-9093  System.err              top.saymzx.easycontrol.app           W  	at libcore.io.Linux.connect(Native Method)
2023-11-01 11:12:51.490  7314-9093  System.err              top.saymzx.easycontrol.app           W  	at libcore.io.ForwardingOs.connect(ForwardingOs.java:204)
2023-11-01 11:12:51.490  7314-9093  System.err              top.saymzx.easycontrol.app           W  	at libcore.io.BlockGuardOs.connect(BlockGuardOs.java:157)
2023-11-01 11:12:51.490  7314-9093  System.err              top.saymzx.easycontrol.app           W  	at libcore.io.ForwardingOs.connect(ForwardingOs.java:204)
2023-11-01 11:12:51.490  7314-9093  System.err              top.saymzx.easycontrol.app           W  	at libcore.io.IoBridge.connectErrno(IoBridge.java:202)
2023-11-01 11:12:51.490  7314-9093  System.err              top.saymzx.easycontrol.app           W  	at libcore.io.IoBridge.connect(IoBridge.java:180)
2023-11-01 11:12:51.491  7314-9093  System.err              top.saymzx.easycontrol.app           W  	... 13 more
```

**Comment by mingzhixian** [comment]
failed to connect to /192.168.0.209 (port 5555) from /:: (port 40156): connect failed: ECONNREFUSED (Connection refused)
这是你的网络问题，请自行检查，注意ipv4和ipv6

**Comment by Layne2016** [comment]
![image](https://github.com/mingzhixian/Easycontrol/assets/20057050/fadb3f70-c7ea-4f3e-8094-66950dac9b3d)

好吧，好像确实是这台设备有问题，已经打开了无线调试，电脑也一样连接不上

**Comment by mingzhixian** [comment]
你检查一下地址有没有搞错，第一行命令是没问题的，看一下第二行地址是不是找错了，可以在被控端安装易控，易控设置下面关于选项里有查看本机地址

**Comment by Layne2016** [comment]
确认过了地址没问题，这台设备不是普通手机，是定制过的工业设备，有线连接可以免授权，应该是系统被魔改过了
